# Generated by Django 4.2.13 on 2024-05-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingeniero_en_jefe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("edad", models.SmallIntegerField(max_length=2)),
            ],
            options={
                "verbose_name": "Ingeniero Jefe",
                "verbose_name_plural": "Ingenieros Jefes",
            },
        ),
        migrations.CreateModel(
            name="Obrero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                ("edad", models.SmallIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20, unique=True)),
                (
                    "ingeniero_en_jefe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="empleados.ingeniero_en_jefe",
                        verbose_name="Ingeniero en jefe",
                    ),
                ),
                ("obrero", models.ManyToManyField(to="empleados.obrero")),
            ],
            options={
                "verbose_name": "Seccion",
                "verbose_name_plural": "Secciones",
            },
        ),
    ]
