# Generated by Django 4.2.13 on 2024-05-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingeniero_en_jefe",
            name="edad",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="obrero",
            name="edad",
            field=models.SmallIntegerField(),
        ),
    ]
