# Generated by Django 4.2.13 on 2024-05-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0002_alter_ingeniero_en_jefe_edad_alter_obrero_edad"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingeniero_en_jefe",
            options={
                "verbose_name": "Ingeniero ",
                "verbose_name_plural": "Ingenieros ",
            },
        ),
        migrations.AlterField(
            model_name="seccion",
            name="ingeniero_en_jefe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empleados.ingeniero_en_jefe",
                verbose_name="Ingeniero ",
            ),
        ),
        migrations.RemoveField(
            model_name="seccion",
            name="obrero",
        ),
        migrations.AddField(
            model_name="seccion",
            name="obrero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empleados.obrero",
                verbose_name="Obrero",
            ),
        ),
    ]
