# Generated by Django 4.2.13 on 2024-05-16 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0003_alter_ingeniero_en_jefe_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seccion",
            old_name="ingeniero_en_jefe",
            new_name="ingeniero",
        ),
    ]
